apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "19"
  creationTimestamp: "2022-07-08T02:12:41Z"
  generation: 59
  labels:
    name: test-bigip-controller-1
  name: test-bigip-controller-1
  namespace: kube-system
  resourceVersion: "5013762"
  uid: 53cf83e5-4638-4aaf-a01b-6a029aea823a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-bigip-controller-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-bigip-controller-1
    spec:
      containers:
      - args:
        - --bigip-partition
        - test
        - --bigip-url
        - 10.145.69.210
        - --bigip-username
        - admin
        - --bigip-password
        - admin
        - --log-level
        - DEBUG
        - --as3-validation=true
        - --disable-teems=true
        - --insecure
        - --log-as3-response=true
        - --custom-resource-mode=true
        - --pool-member-type
        - nodeport
        - --namespace
        - istio-gateway
        command:
        - /app/bin/k8s-bigip-ctlr
        image: f5networks/k8s-bigip-ctlr:2.9.0
        imagePullPolicy: IfNotPresent
        name: test-bigip-controller-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bigip-controller
      serviceAccountName: bigip-controller
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-07-08T02:12:41Z"
    lastUpdateTime: "2022-07-08T03:27:27Z"
    message: ReplicaSet "test-bigip-controller-1-5b9667c8f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-07-08T03:29:30Z"
    lastUpdateTime: "2022-07-08T03:29:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 59
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
