apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2022-07-08T02:12:22Z"
  name: bigip-controllers
  resourceVersion: "5006018"
  uid: 012c4d03-dca4-48a9-8bf6-88cdddd46d56
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bigip-controller-role
subjects:
- kind: ServiceAccount
  name: bigip-controller
  namespace: kube-system
